name: apsiyon
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.0
  auto_route: ^7.8.4
  cloud_firestore: ^5.1.0
  collection: ^1.18.0
  country_code_picker: ^3.0.0
  cross_connectivity: ^3.1.0
  cupertino_icons: ^1.0.6
  currency_text_input_formatter: ^2.1.11
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.3
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_animations: ^0.5.3
  flutter_map_geojson: ^1.0.6
  flutter_native_splash: ^2.3.9
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  fluttertoast: ^8.2.4
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  geolocator: ^10.1.0
  get_it: ^7.6.6
  hooks_riverpod: ^2.4.9 
  http_parser: ^4.0.2
  injectable: ^2.3.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  mask_text_input_formatter: ^2.7.0
  mime: ^1.0.4
  package_info_plus: ^8.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  pinput: ^5.0.0
  qr_flutter: ^4.1.0
  sentry_dio: ^8.2.0
  sentry_flutter: ^8.2.0
  shared_preferences: ^2.2.2
  zego_uikit_prebuilt_video_conference: ^2.8.5

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.10
  change_app_package_name: ^1.1.0
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500

    


       
     
      
flutter_gen:
  assets:
    enabled: true
  integrations:
    flutter_svg: true